version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: facade/ignition
    versions:
    - 2.5.10
    - 2.5.11
    - 2.5.12
    - 2.5.13
    - 2.5.14
    - 2.5.9
    - 2.6.0
    - 2.7.0
    - 2.8.2
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
  - dependency-name: sentry/sentry-laravel
    versions:
    - 2.4.1
  - dependency-name: nesbot/carbon
    versions:
    - 2.44.0
    - 2.45.0
    - 2.45.1
  - dependency-name: nunomaduro/collision
    versions:
    - 5.2.0
    - 5.3.0
  - dependency-name: laravel/framework
    versions:
    - 7.30.4
  - dependency-name: laravel/tinker
    versions:
    - 2.6.0
